variables:
  BUCKET: <YOUR_BUCKET_NAME>
  BUILD_DIR: <YOUR_BUILD_DIR>
  HASHED_FILES: <YOUR_HASHED_FILES_DIR>
  CDN_DISTRIBUTION_ID: <YOUR_CDN_DISTRIBUTION_ID>
  INVALIDATE_CACHE: <SHOULD_INVALIDATE_CACHE?>
  INVALIDATION_PATH: <YOUR_INVALIDATION_PATH>
  TTL_TIME: <YOUR_MAX_TTL_TIME>
  AWS_ACCESS_KEY_ID: <YOUR_AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <YOUR_AWS_SECRET_ACCESS_KEY>

  # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are best set in the CI/CD variables
  #   https://docs.gitlab.com/ee/ci/variables/

stages:
  - deploy

deploy:
  image: olmesm/s3-deploy
  stage: deploy
  script:
    - sh /usr/scripts/deploy-s3.sh
    - sh /usr/scripts/deploy-cdn.sh
